language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37
  - python: pypy2.7-5.10.0
    env: TOXENV=pypy
  - python: pypy3.5-5.10.0
    env: TOXENV=pypy3
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=setup.py
  - python: 3.6
    env: TOXENV=perf
# use cache for big builds like pandas (to minimise build time).
# If issues, clear cache
# https://docs.travis-ci.com/user/caching/#Clearing-Caches
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
# branches:  # remove travis double-check on pull requests in main repo
#   only:
#     - master
#     - /^\d\.\d+$/
before_install:
  # fix a crash with multiprocessing on Travis
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
  - git fetch --tags
install:
  - pip install tox
  - pip install .
script:
  - tox
